apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ganesha
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - infisical-zot.yaml
images:
  - name: 127.0.0.1:30500/ganesha
    newTag: prod-f7c36d897be20049dafb5940c2e3d29962f911cf-36075381860-1
    digest: sha256:ca85b1eb3f657419fd749c5c105ab4409c387bdd93d8550ccbfc7ff81f7494e3
