apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ganesha
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - infisical-zot.yaml
images:
  - name: 127.0.0.1:30500/ganesha
    newTag: prod-fcf4e7e5a3f014e0b1cdd9df2d364dbe7924a5f9-36076100786-1
    digest: sha256:060ec66b4fa286affcf1dca89c246ef2d4883a3519201cb43020e19778dc0112
